### ISSUE TITLE
Missing push notification entitlement

### ISSUE THREAD

**Issue by munhra** [munhra/IrishCofee#116]
Solve the following issue.

Dear developer,

We have discovered one or more issues with your recent delivery for "caffinhoVNT". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

Missing Push Notification Entitlement - Your app includes an API for Apple's Push Notification service, but the aps-environment entitlement is missing from the app's signature. To resolve this, make sure your App ID is enabled for push notification in the Provisioning Portal. Then, sign your app with a distribution provisioning profile that includes the aps-environment entitlement. This will create the correct signature, and you can resubmit your app. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

Regards,

The App Store team

**Comment by silvanosouzajunior** [comment]
Below we have a comment from an Apple Staff Member explain that this warning is caused by a third library that we are probably using, but that is safe to ignore that, without the rejection risk on the App Store.

"That notice is a warning only, not a rejection.
 
The app validator checks for an implementation of the UIApplicationDelegate method application:didRegisterForRemoteNotificationsWithDeviceToken: in the app. You’ll get the warning you described if your app delegate implements that method and there is no aps-environment entitlement.
 
It's possible that a third-party library you're using has implemented that method even though your app doesn't do anything with push notifications. In that case you can just ignore the warning. It's there to let developers who do use push notifications know if they might have signed their app incorrectly"

https://forums.developer.apple.com/thread/11704
